import unittest

from day08 import count_antinodes, count_antinodes_harmonic, parse_grid

EXAMPLE_ANTENNAS = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""


class Day08TestCase(unittest.TestCase):
    def test_example_data(self):
        grid = parse_grid(EXAMPLE_ANTENNAS)
        with self.subTest("Part 1"):
            self.assertEqual(count_antinodes(grid), 14)
        with self.subTest("Part 2"):
            self.assertEqual(count_antinodes_harmonic(grid), 34)
